### ISSUE TITLE
Set transfer pass splitting style

### ISSUE THREAD

**Issue by ixchow** [textiles-lab/knitout-backend-kniterate#5]
Currently, the backend always splits a transfer pass into (up to) four sub-passes:
- back-to-front, even transfers (as in, even index within the list of all back-to-front xfers)
- back-to-front, odd transfers
- front-to-back, even transfers
- front-to-back, odd transfers

This is "safe" or "fancy" behavior, depending on how you want to spin it. It might make sense to have a header or extension to select the "fast" behavior.

**Comment by kausalyamahadevan** [comment]
Something else to keep in mind: If you're transferring edge needles back and forth frequently (e.g. for garter stitch), it seems to work much better to transfer the edges on the first pass -- they often get dropped if the second-to-last needle transfers first. Right now that can only be solved by forcing a sample to be an even (or odd) needle size, it would be good to tell the backend to transfer the edges on the first pass, or something similar.

**Comment by vsanchez01** [comment]
![IMG_8921](https://user-images.githubusercontent.com/75637958/109703142-2228a580-7b63-11eb-9511-61213a6848e4.jpg)
![IMG_8922](https://user-images.githubusercontent.com/75637958/109703150-248aff80-7b63-11eb-8f6e-d768f5cf538b.jpg)

Adding some images to show the results of having edges transfer on the first pass and having the right edge transfer on the last (in this case second) pass

**Comment by ixchow** [comment]
Supported by extension `x-xfer-style` as of 3b09707703816736e6a22c66048d5b6c905f0ee7 .

Usage:
```
;perform xfers in "front->back, even", "front->back, odd", "back->front, even", and "back->front, odd" passes:
x-xfer-style four-pass
;perform xfers in "front->back" and "back->front" passes:
x-xfer-style two-pass
```

Until we have an instruction to explicitly divide passes (#6), you need to use a hack (adding a `miss`) if you are trying to explicitly divide up `xfers`. This is not ideal because a future backend could conceivably optimize the `miss` out and still merge the passes:
```
x-xfer-style two-pass
; these will all get performed in the same pass:
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f2 b2
xfer f4 b4
xfer f6 b6
; by adding a non-xfer instruction you can break the passes:
xfer f1 b1
xfer f3 b3
xfer f5 b5
miss + f1 5
xfer f2 b2
xfer f4 b4
xfer f6 b6
```

**Comment by ixchow** [comment]
With `x-end-pass`, one may now write:
```
x-xfer-style two-pass
xfer f1 b1
xfer f3 b3
xfer f5 b5
x-end-pass
xfer f2 b2
xfer f4 b4
xfer f6 b6
```

I believe this provides the needed functionality for now. We may revisit this if even more explicit control over `xfer` ordering is required.
